INSERT INTO SHIFT5_CATEGORIA (ID_CATEGORIA, NOME_CATEGORIA, ATIVO) VALUES (CATEGORIA_SEQ.NEXTVAL, 'Notebook', 1);
INSERT INTO SHIFT5_CATEGORIA (ID_CATEGORIA, NOME_CATEGORIA, ATIVO) VALUES (CATEGORIA_SEQ.NEXTVAL, 'Smartphone', 1);
INSERT INTO SHIFT5_CATEGORIA (ID_CATEGORIA, NOME_CATEGORIA, ATIVO) VALUES (CATEGORIA_SEQ.NEXTVAL, 'TV', 1);
INSERT INTO SHIFT5_CATEGORIA (ID_CATEGORIA, NOME_CATEGORIA, ATIVO) VALUES (CATEGORIA_SEQ.NEXTVAL, 'Tablet', 0);


INSERT INTO SHIFT5_MARCA (ID_MARCA, NOME_MARCA) VALUES (MARCA_SEQ.NEXTVAL, 'LG');
INSERT INTO SHIFT5_MARCA (ID_MARCA, NOME_MARCA) VALUES (MARCA_SEQ.NEXTVAL, 'Apple');
INSERT INTO SHIFT5_MARCA (ID_MARCA, NOME_MARCA) VALUES (MARCA_SEQ.NEXTVAL, 'Samsumg');
INSERT INTO SHIFT5_MARCA (ID_MARCA, NOME_MARCA) VALUES (MARCA_SEQ.NEXTVAL, 'Sony');


INSERT INTO SHIFT5_PRODUTO (ID_PRODUTO, NOME, SKU, DESCRICAO, CARACTERISTICAS, PRECO, DATA_LANCAMENTO, ID_CATEGORIA, FOTO) VALUES (PRODUTO_SEQ.NEXTVAL, 'LG Nome do produto 1', 'sku-0001', 'Descrição do Produto 1', 'Características do produto 1', 1.99, TO_DATE('2003/05/03', 'yyyy/mm/dd') , 1,
INSERT INTO SHIFT5_PRODUTO (ID_PRODUTO, NOME, SKU, DESCRICAO, CARACTERISTICAS, PRECO, DATA_LANCAMENTO, ID_CATEGORIA, FOTO) VALUES (PRODUTO_SEQ.NEXTVAL, 'APPLE Nome do produto 2', 'sku-0002', 'Descrição do Produto 2', 'Características do produto 2', 2.99, TO_DATE('2003/06/03', 'yyyy/mm/dd') , 2,
INSERT INTO SHIFT5_PRODUTO (ID_PRODUTO, NOME, SKU, DESCRICAO, CARACTERISTICAS, PRECO, DATA_LANCAMENTO, ID_CATEGORIA, FOTO) VALUES (PRODUTO_SEQ.NEXTVAL, 'FIAP Nome do produto 3', 'sku-0002', 'Descrição do Produto 3', 'Características do produto 3', 3.99, TO_DATE('2003/07/03', 'yyyy/mm/dd') , 3,

INSERT INTO SHIFT5_LOJA (ID_LOJA, NOME_LOJA) VALUES (LOJA_SEQ.NEXTVAL, 'Americanas');
INSERT INTO SHIFT5_LOJA (ID_LOJA, NOME_LOJA) VALUES (LOJA_SEQ.NEXTVAL, 'Fast Shop');
INSERT INTO SHIFT5_LOJA (ID_LOJA, NOME_LOJA) VALUES (LOJA_SEQ.NEXTVAL, 'Magazine Luiza');
INSERT INTO SHIFT5_LOJA (ID_LOJA, NOME_LOJA) VALUES (LOJA_SEQ.NEXTVAL, 'Submarino');

INSERT INTO SHIFT5_PRODUTO_LOJA (ID_PRODUTO , ID_LOJA) VALUES ( 1 , 1 );
INSERT INTO SHIFT5_PRODUTO_LOJA (ID_PRODUTO , ID_LOJA) VALUES ( 1 , 2 );
INSERT INTO SHIFT5_PRODUTO_LOJA (ID_PRODUTO , ID_LOJA) VALUES ( 1 , 3 );
INSERT INTO SHIFT5_PRODUTO_LOJA (ID_PRODUTO , ID_LOJA) VALUES ( 1 , 4 );
INSERT INTO SHIFT5_PRODUTO_LOJA (ID_PRODUTO , ID_LOJA) VALUES ( 2 , 1 );
INSERT INTO SHIFT5_PRODUTO_LOJA (ID_PRODUTO , ID_LOJA) VALUES ( 2 , 2 );
INSERT INTO SHIFT5_PRODUTO_LOJA (ID_PRODUTO , ID_LOJA) VALUES ( 2 , 3 );
INSERT INTO SHIFT5_PRODUTO_LOJA (ID_PRODUTO , ID_LOJA) VALUES ( 2 , 4 );
INSERT INTO SHIFT5_PRODUTO_LOJA (ID_PRODUTO , ID_LOJA) VALUES ( 3 , 1 );
INSERT INTO SHIFT5_PRODUTO_LOJA (ID_PRODUTO , ID_LOJA) VALUES ( 3 , 2 );
INSERT INTO SHIFT5_PRODUTO_LOJA (ID_PRODUTO , ID_LOJA) VALUES ( 3 , 3 );
INSERT INTO SHIFT5_PRODUTO_LOJA (ID_PRODUTO , ID_LOJA) VALUES ( 3 , 4 );
INSERT INTO SHIFT5_PRODUTO_LOJA (ID_PRODUTO , ID_LOJA) VALUES ( 4 , 1 );
INSERT INTO SHIFT5_PRODUTO_LOJA (ID_PRODUTO , ID_LOJA) VALUES ( 4 , 3 );


INSERT INTO SHIFT5_USUARIO ( ID_USUARIO , CPF, NOME, EMAIL, SENHA, FOTO, IDADE ) VALUES ( USUARIO_SEQ.NEXTVAL, '111','USER 1', 'USER1@EMAIL.COM',
INSERT INTO SHIFT5_USUARIO ( ID_USUARIO , CPF, NOME, EMAIL, SENHA, FOTO, IDADE ) VALUES ( USUARIO_SEQ.NEXTVAL, '222','USER 2', 'USER1@EMAIL.COM',
INSERT INTO SHIFT5_USUARIO ( ID_USUARIO , CPF, NOME, EMAIL, SENHA, FOTO, IDADE ) VALUES ( USUARIO_SEQ.NEXTVAL, '333','USER 3', 'USER1@EMAIL.COM',
INSERT INTO SHIFT5_USUARIO ( ID_USUARIO , CPF, NOME, EMAIL, SENHA, FOTO, IDADE ) VALUES ( USUARIO_SEQ.NEXTVAL, '444','USER 4', 'USER1@EMAIL.COM',
