INSERT INTO SHIFT5_CATEGORIA (ID_CATEGORIA, NOME_CATEGORIA, ATIVO) VALUES (CATEGORIA_SEQ.NEXTVAL, 'Notebook', 1);
INSERT INTO SHIFT5_CATEGORIA (ID_CATEGORIA, NOME_CATEGORIA, ATIVO) VALUES (CATEGORIA_SEQ.NEXTVAL, 'Smartphone', 1);
INSERT INTO SHIFT5_CATEGORIA (ID_CATEGORIA, NOME_CATEGORIA, ATIVO) VALUES (CATEGORIA_SEQ.NEXTVAL, 'TV', 1);
INSERT INTO SHIFT5_CATEGORIA (ID_CATEGORIA, NOME_CATEGORIA, ATIVO) VALUES (CATEGORIA_SEQ.NEXTVAL, 'Tablet', 0);

INSERT INTO SHIFT5_USUARIO ( ID_USUARIO, CPF, NOME, EMAIL, SENHA, FOTO, IDADE ) VALUES ( 1, '111','USER 1', 'USER1@EMAIL.COM', '111111', 'http://1.com', 11)
INSERT INTO SHIFT5_USUARIO ( ID_USUARIO, CPF, NOME, EMAIL, SENHA, FOTO, IDADE ) VALUES ( 2, '222','USER 2', 'USER1@EMAIL.COM', '222222', 'http://2.com', 22)
INSERT INTO SHIFT5_USUARIO ( ID_USUARIO, CPF, NOME, EMAIL, SENHA, FOTO, IDADE ) VALUES ( 3, '333','USER 3', 'USER1@EMAIL.COM', '333333', 'http://3.com', 33)
INSERT INTO SHIFT5_USUARIO ( ID_USUARIO, CPF, NOME, EMAIL, SENHA, FOTO, IDADE ) VALUES ( 4, '444','USER 4', 'USER1@EMAIL.COM', '444444', 'http://4.com', 44)

